-- :help options
local opt=vim.opt
opt.backup = false				-- crea un archivo de backup
opt.clipboard = "unnamedplus"			-- permite que neovim acceda al portapapeles del sistema
opt.cmdheight = 2				-- más espacio en la línea de comandos de neovim para mostrar mensajes
opt.completeopt = { "menuone", "noselect"}	-- principalmente solo para cmp
opt.conceallevel = 0				-- para que `` sea visible en los archivos de markdown
opt.fileencoding = "utf-8"			-- la codificación escrita en un archivo
opt.hlsearch = true				-- resaltar todas las coincidencias en el patrón de búsqueda anterior
opt.ignorecase = true				-- ignorar mayúsculas y minúsculas en patrones de búsqueda
opt.mouse = "a"					-- permitir que el mouse se use en neovim
opt.pumheight = 10				-- altura del menú emergente
opt.showmode = false				-- ya no necesitamos ver cosas como -- INSERT --
opt.showtabline = 2				-- mostrar siempre pestañas
opt.smartcase = true				-- funda inteligente
opt.smartindent = true				-- hacer sangría más inteligente de nuevo
opt.splitbelow = true				-- obligar a todas las divisiones horizontales a ir debajo de la ventana actual
opt.splitright = true				-- obligar a todas las divisiones verticales a ir a la derecha de la ventana actual
opt.swapfile = false				-- crea un archivo swap
opt.termguicolors = true			-- establecer los colores de la interfaz gráfica de usuario (la mayoría de los terminales lo admiten)
opt.timeoutlen = 1000				-- tiempo de espera para que se complete una secuencia mapeada (en milisegundos)
opt.undofile = true				-- habilitar deshacer persistente
opt.updatetime = 300				-- finalización más rápida (4000 ms por defecto)
opt.writebackup = false				-- si otro programa está editando un archivo no se permite editarlo
opt.expandtab = true				-- convertir tabulaciones en espacios
opt.shiftwidth = 2				-- el número de espacios insertados para cada sangría
opt.tabstop = 2					-- insertar 2 espacios para una tabulación
opt.cursorline = false				-- resaltar la línea actual
opt.number = true				-- establecer líneas numeradas
opt.relativenumber = true			-- establecer líneas numeradas relativas
opt.numberwidth = 4				-- establecer el ancho de columna de número en 2 {predeterminado 4}
opt.signcolumn = "yes"				-- mostrar siempre la columna de signo, de lo contrario cambiaría el texto cada vez
opt.wrap = true				-- mostrar líneas como una línea larga
opt.scrolloff = 8				-- Desplazamiento 
opt.sidescrolloff = 8				-- Desplazamiento lateral
opt.sidescrolloff = 8				-- la fuente utilizada en las aplicaciones gráficas de neovim
